# ASSIGNMENT ON NUMPY 

# QUESTION 1

## You're given student test scores.Create a program that performs basic analysis:

In [ ]:
 # python
    student_scores=[
        [85,92,78,96,88], #student 1's scores across 5
tests
        [79,85,91,87,83], #student 2
        [92,88,95,91,89], #student 3
        [76,82,79,85,81], #student 4
        [88,91,87,93,90],
    ]
Tasks:
1.convert to numpy array and explore its properties
2.calculate each student's average score using array operations
3.find the highest and lowest score in the entire dataset
4.identify which test(column) had the highest average score
5.create a boolean array showing scores above 90
6.use slicing to get the first 3 student's scores on the last 2 tests

In [15]:
import numpy as np
student_scores=[
    [85,92,78,96,88],
    [79,85,91,87,83],
    [92,88,95,91,89],
    [76,82,79,85,81],
    [88,91,87,93,90]
]
# convert to numpy array
scores=np.array(student_scores)
# 1.explore properties
print("array:/n", scores)
print("shape:", scores_array.shape)
print("data type:",scores_array.dtype)
print("number of dimensions",scores_array.ndim)

array:/n [[85 92 78 96 88]
 [79 85 91 87 83]
 [92 88 95 91 89]
 [76 82 79 85 81]
 [88 91 87 93 90]]
shape: (5, 5)
data type: int32
number of dimensions 2


In [16]:
# calculate each student's averages score
student_averages=scores.mean(axis=1)
print ("student averages score:", student_averages)

student averages score: [87.8 85.  91.  80.6 89.8]


In [17]:
# highest and lowest score in dataset
highest_score=scores.max()
lowest_score=scores.min()
print("highest_score:", highest_score)
print("lowest_score:", lowest_score)

highest_score: 96
lowest_score: 76


In [19]:
# Test(colum) with highest average score
test_averages=scores.mean(axis=0)
highest_avg_test_index=np.argmax(test_averages)
print("test averages:", test_averages)
print("test with highest average (0-based index):",highest_avg_test_index)

test averages: [84.  87.6 86.  90.4 86.2]
test with highest average (0-based index): 3


In [20]:
# Boolean array for scores above 90
above_90=scores>90
print("scores>90:/n", above_90)

scores>90:/n [[False  True False  True False]
 [False False  True False False]
 [ True False  True  True False]
 [False False False False False]
 [False  True False  True False]]


In [24]:
# first 3 students,last 2 tests
subset=scores[:3,-2:]
print("First 3 students,last 2 tests:/n:", subset)

First 3 students,last 2 tests:/n: [[96 88]
 [87 83]
 [91 89]]


 # QUESTION 2 

# Analyze student performance across multiple subjects:

In [2]:
import numpy as np
# date setup
np.random.seed(456)
num_students, num_subjects=50,6
subject_name=["math", "Science", "English", "History", "Art", "PE"]
scores=np.random.randint(60,100, (num_students, num_subjects))
print(scores)

[[87 97 85 88 75 97]
 [88 99 77 71 73 65]
 [94 74 80 94 62 64]
 [68 81 98 76 70 68]
 [95 95 82 95 82 70]
 [81 77 66 91 71 81]
 [86 85 72 80 62 64]
 [75 65 64 81 91 93]
 [70 87 85 64 71 90]
 [88 65 67 83 72 85]
 [75 80 77 86 92 74]
 [72 68 95 68 75 87]
 [75 90 76 99 70 93]
 [96 67 79 97 85 74]
 [80 94 73 71 86 86]
 [84 89 64 99 88 69]
 [82 60 86 60 71 71]
 [84 73 73 97 98 82]
 [63 75 89 98 81 76]
 [98 75 71 81 83 78]
 [62 93 70 85 62 96]
 [76 62 66 79 73 77]
 [98 77 60 86 87 67]
 [92 73 69 72 74 69]
 [75 91 71 94 65 91]
 [64 80 85 65 73 64]
 [83 92 66 79 69 65]
 [89 99 89 88 73 66]
 [69 72 89 71 68 80]
 [78 91 71 90 84 84]
 [96 69 60 61 92 78]
 [91 74 94 63 67 89]
 [73 79 66 64 75 97]
 [74 75 93 74 70 93]
 [62 84 65 98 91 80]
 [70 66 96 87 64 86]
 [66 62 88 98 66 97]
 [76 87 83 81 78 89]
 [99 73 84 81 82 67]
 [78 65 95 77 86 73]
 [73 70 97 85 99 86]
 [94 61 64 93 91 83]
 [91 98 83 87 99 67]
 [91 87 94 86 77 89]
 [69 88 98 74 67 83]
 [60 90 84 90 98 66]
 [66 99 94 89 94 94]
 [76 79 67 94

# student who excel in stem (Math + science average >90)

In [11]:
import numpy as np
np.random.seed(456)
scores=np.random.randint(60,100, (50,6))
subject_names=["Math", "Science", "English", "History", "Art", "PE"]
Math_idx=subject_names.index("Math") # shape (50)
science_idx=subject_names.index("Science") # shape (50,)
stem_avg=(scores[:, Math_idx] + scores[:, science_idx]) /2
stem_excellent=np.where(stem_avg>90)[0]
print("students excelling in STEM:", stem_excellent)

students excelling in STEM: [ 0  1  4 27 42]


# B.identify struggling students(any subject<70) and which subjects they struggle with

In [15]:
struggling_student={}
for i in range(num_students):
    weak_subjects=[subject_name[j] for j in range(num_subjects) if scores[i,j]>70]
    if weak_subjects:
        print(f"student {i}: {weak_subjects}")

student 0: ['math', 'Science', 'English', 'History', 'Art', 'PE']
student 1: ['math', 'Science', 'English', 'History', 'Art']
student 2: ['math', 'Science', 'English', 'History']
student 3: ['Science', 'English', 'History']
student 4: ['math', 'Science', 'English', 'History', 'Art']
student 5: ['math', 'Science', 'History', 'Art', 'PE']
student 6: ['math', 'Science', 'English', 'History']
student 7: ['math', 'History', 'Art', 'PE']
student 8: ['Science', 'English', 'Art', 'PE']
student 9: ['math', 'History', 'Art', 'PE']
student 10: ['math', 'Science', 'English', 'History', 'Art', 'PE']
student 11: ['math', 'English', 'Art', 'PE']
student 12: ['math', 'Science', 'English', 'History', 'PE']
student 13: ['math', 'English', 'History', 'Art', 'PE']
student 14: ['math', 'Science', 'English', 'History', 'Art', 'PE']
student 15: ['math', 'Science', 'History', 'Art']
student 16: ['math', 'English', 'Art', 'PE']
student 17: ['math', 'Science', 'English', 'History', 'Art', 'PE']
student 18: ['Sc

# Most challenging subject(lowest average) and best performers in that subject

In [28]:
subject_avg=scores.mean(axis=0)
lowest_idx=np.argmin(subject_avg)
most_challenging=subject_names[lowest_idx]
print("/nmost challenging subject:", most_challenging)
print("average score:", subject_avg[lowest_idx])
#  Best performers in that subject
max_score=np.max(scores[:, lowest_idx])
top_students=np.where(scores[:, lowest_idx]== max_score)[0]
print("top-performing students:", top_students)
print("highest score:", max_score)

/nmost challenging subject: Art
average score: 78.42
top-performing students: [40 42]
highest score: 99


# QUESTION 3

# Analying a stock portfolio using numpy's mathematical function

In [8]:
import numpy as np 
np.random.seed(789)
days=252
stocks=5
daily_return=np.random.normal(0.001,0.02, (days,stocks))
stock_names=["AAPL", "GOOGL", "MSFT", "TSLA", "AMZN"]
initial_prices=np.array([150,2800,300,800,3200])
# best analysis
cumulative_returns = np.cumprod(1+daily_returns, axis=0)-1
final_returns=cumulative_returns[-1]
# annualized volatility
volatility=np.std(daily_returns, axis=0)*np.sqrt(252)
#best and worse performers
best_idx=np.argmax(final_returns)
worse_idx=np.argmin(final_returns)
print("final cumulative returns:")
for i in range(stocks):
    print(f"{stock_names[i]}: {final_returns[i]:.2%}")
print(f"/nbest performing stock: {stock_names[best_idx]}")
print(f"/nbest performing stock: {stock_names[worse_idx]}")

final cumulative returns:
AAPL: 1.87%
GOOGL: 38.29%
MSFT: -7.64%
TSLA: 157.90%
AMZN: 17.11%
/nbest performing stock: TSLA
/nbest performing stock: MSFT


# Risk metrics

In [11]:
# sharpe rotio (assuming risk-free rate = 0)
mean_returns=np.mean(daily_returns,axis=0)*252
sharpe_ratio=mean_returns/volatility
print("/nsharpe ratios:")
for i in range(stocks):
    print(f"{stock_names[i]}: {sharpe_ratio[i]:.2f}")

/nsharpe ratios:
AAPL: 0.22
GOOGL: 1.12
MSFT: -0.11
TSLA: 3.09
AMZN: 0.68


In [15]:
# maximum drawdown
def max_drawdown(returns):
    cumulative=np.cumprod(1+returns)
    peak=np.maximum.accumulate(cumulative)
    drawdown=(cumulative-peak)/peak
    return np.min(drawdown)
print("/nmaximum drawdown:")
for i in range(stocks):
    mdd=max_drawdown(daily_returns[:,i])
    print(f"{stock_names[i]}: {mdd:2%}")

/nmaximum drawdown:
AAPL: -22.714481%
GOOGL: -28.661051%
MSFT: -43.894286%
TSLA: -11.172979%
AMZN: -21.783847%


In [16]:
# correlation matrix
correlation_matrix=np.corrcoef(daily_returns.T)
print("/ncorrelation matrix:")
print(correlation_matrix)

/ncorrelation matrix:
[[ 1.          0.01558858  0.0016994  -0.10262945  0.08717904]
 [ 0.01558858  1.         -0.15014226  0.08813674  0.03835865]
 [ 0.0016994  -0.15014226  1.          0.01366414 -0.02847043]
 [-0.10262945  0.08813674  0.01366414  1.         -0.11192288]
 [ 0.08717904  0.03835865 -0.02847043 -0.11192288  1.        ]]
